### ISSUE TITLE
How to use localization for the text bound to paper-dropdown item

### ISSUE THREAD

**Issue by sumukhj84** [jshcrowthe/wc-i18n#1]
How i can use this element to localize the text in the paper dropdown but the items are bound dynamically to the paper dropdown.? Any example?

**Comment by jshcrowthe** [comment]
I want to make sure I am understanding properly before I go put something together for you. You want to have a list of locales and iterate over that list (presumably using `dom-repeat` or something of the like) and generate `paper-item` tags?

**Comment by sumukhj84** [comment]
Correct.I am looking for the same. Change the paper-item values as per the language suppose i have a list contain days, months which i am binding through the dom-repeat. then i want to display them as per the selected language.

**Comment by jshcrowthe** [comment]
Thanks a bunch for the issue. I have added a demo to the demos page of specifically your use case.

In addition to that while building the demo a quick 2 second feature made my life much easier. I have added the feature to master and cut a new release. Take a look and let me know what you think!

**Comment by sumukhj84** [comment]
Thank you for the quick response, appreciated!!. I will take a look at it and let you know.

**Comment by sumukhj84** [comment]
Hi Josh,

I did see 1 issue that when ou change the language the selected item from list does not change and it displays in the same language which was selected earlier.For example, if you have selected language as english you select month as March then again you change the language to Ko then it does not change the locale of elected item but it changes the locale in the list.

Thanks,
Sumukh

**Comment by sumukhj84** [comment]
Hi Josh,

I did see 1 issue that when ou change the language the selected item from list does not change and it displays in the same language which was selected earlier.For example, if you have selected language as english you select month as March then again you change the language to Ko then it does not change the locale of elected item but it changes the locale in the list.

Thanks,
Sumukh

**Comment by jshcrowthe** [comment]
You raise a valid point! This is due to the label being used as the value in the paper-dropdown. You simply need to separate the label from the value (like you do in `option` tags: `<option label='[[I18N VALUE HERE]]' value='val'>`) and this is not an issue.
