### ISSUE TITLE
Rendering translations with HTML tags

### ISSUE THREAD

**Issue by dcravenus** [jshcrowthe/wc-i18n#11]
The previous version of wc-i18n supported rendering HTML included within translation strings.  This feature is missing from version 2.

**Comment by jshcrowthe** [comment]
You can data bind to the `inner-h-t-m-l` attribute on an element to set the `innerHTML` value of an element. This is not **explicitly** supported by Polymer but, if you have to inject raw HTML, is a solution that has been suggested (see https://github.com/Polymer/polymer/pull/3362 for a discussion on this).

An example so it all makes sense: http://jsbin.com/miyuso/20/edit?html,css
_NOTE: If you can't get that JSBin to render in the output window, visit http://output.jsbin.com/miyuso/20 for a working example. I sometimes have issues with the output pane_

Another possible solution to this would be to create an `unsafe-html` element or something of the like and inject the content there. That said, that would be outside of the scope of this element.
