### ISSUE TITLE
paper dropdown selected item is not localized.

### ISSUE THREAD

**Issue by sumukhj84** [jshcrowthe/wc-i18n#3]
Hi Josh,

I did see 1 issue that when ou change the language the selected item from list does not change and it displays in the same language which was selected earlier.For example, if you have selected language as english you select month as March then again you change the language to Ko then it does not change the locale of elected item but it changes the locale in the list.

Thanks,
Sumukh

**Comment by jshcrowthe** [comment]
You raise a valid point! This is due to the label being used as the value in the paper-dropdown. You simply need to separate the label from the value (like you do in option tags: <option label='[[I18N VALUE HERE]]' value='val'>) and this is not an issue.
