### ISSUE TITLE
How to use AJAX feature in your component.

### ISSUE THREAD

**Issue by sumukhj84** [jshcrowthe/wc-i18n#4]
Your component is awsome!! how i can use the AJAX behavior to load the locales as you mentioned in your docs.

**Comment by jshcrowthe** [comment]
Thanks for using it! Feel free to give it a star!

As for your question take a look at: https://github.com/jshcrowthe/wc-i18n/blob/master/demo/demo-comp/demo-comp.html

It shows an example of creating a component that includes the required behavior and implements the function properly.

**Comment by sumukhj84** [comment]
Thanks Josh for your help. I will take a look at it.

**Comment by jshcrowthe** [comment]
I am going to close this, let me know if you have questions.
